language: node_js
node_js:
- node
script:
- npm run build
before_install:
- openssl aes-256-cbc -K $encrypted_62a3e116008b_key -iv $encrypted_62a3e116008b_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host ${deploy_host}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- cd $TRAVIS_BUILD_DIR/dist
- tar zcvf ../aqua.tar.gz .
- cd $TRAVIS_BUILD_DIR
- scp -P $deploy_port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  aqua.tar.gz ${deploy_user}@${deploy_host}:/var/www/aqua/
- ssh -p $deploy_port -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
  ${deploy_user}@${deploy_host} 'cd /var/www/aqua && tar zxvf aqua.tar.gz && rm -f
  aqua.tar.gz'
